name: CD Build the docker and push to registry
on:
  workflow_dispatch:
    workflows:
      ['CI Run Tests and Build Docker Image']
    types:
      - completed
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: build docker image
        run: |
          docker build -t skin-cancer-api:latest ./project

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag skin-cancer-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/skin-cancer-api:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/skin-cancer-api:latest